import { AiFillStar } from "react-icons/ai";

const data = [
  {
    img: "https://m.media-amazon.com/images/I/6125yAfsJKL._AC_UX575_.jpg",
    img1: "https://m.media-amazon.com/images/I/61JiTAo1HWL._AC_SX575_.jpg",
    img2: "https://m.media-amazon.com/images/I/61FwDD6em2L._AC_SX575_.jpg",
    details:
      "This shoe model by Nike is from the trainers category; These men's shoes in white impress with a clear design and emphasise the current shoe fashion; These large shoes from Nike are perfectly adapted to the urban fashion spirit and add the right touch to any modern as well as classic sporty outfit; The upper material of this model is made of leather, while textile has been used as interior material; -",
    title: "Nike Air Monarch IV",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "white",
    category: "sneakers",
    id: 1,
  },
  {
    img: "https://m.media-amazon.com/images/I/519MRhRKGFL._AC_UX575_.jpg",
    img1: "https://m.media-amazon.com/images/I/51IHWwiSYES._AC_SX679_.jpg",
    img2: "https://m.media-amazon.com/images/I/61vpX7zSORL._AC_SX679_.jpg",
    details:
      "Nike Vapormax Plus Men, Men's Sizing to Women Sizing 9M=10.5W, Color: Black/Bright Crimson",
    title: "Nike Air Vapormax Plus",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "red",
    category: "sneakers",
    id: 2,
  },

  {
    img: "https://m.media-amazon.com/images/I/51+P9uAvb1L._AC_UY695_.jpg",
    img1: "https://m.media-amazon.com/images/I/51n1wPtHEAL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/61Qy5vpuUuL._AC_SY395_.jpg",
    details:
      "Nike, Mens Shoes, Fashion Shoes, Black/Blue/Brown, Synthetic & Rubber",
    title: "Nike Waffle One Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    id: 3,
  },
  {
    img: "https://m.media-amazon.com/images/I/71oEKkghg-L._AC_UX575_.jpg",
    img1: "https://m.media-amazon.com/images/I/51t3v0drWbL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71zaPClYYxL._AC_SX395_.jpg",
    details:
      "LIGHTWEIGHT CUSHIONING: Soft foam midsole delivers a smooth, stable ride, making these the running shoes men need. Textured outer wall reduces the weight of the shoe.",
    title: "Nike Running Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "black",
    category: "sneakers",
    id: 4,
  },
  {
    img: "https://m.media-amazon.com/images/I/51wkKxUhcJL._AC_SY395_.jpg",
    img1: "https://m.media-amazon.com/images/I/51dwT2p8bFL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/514ufcee46L._AC_SY395_.jpg",
    details:
      "Special Design: Pointed toe, slip on and low block hidden heel design elongates the foot giving it a sexy look. Comfy:Soft sole and Classic low block hidden heel is concise and bring more convenice when slip on them",
    title: "Flat Slip On Pumps",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Vans",
    color: "green",
    category: "flats",
    id: 5,
  },
  {
    img: "https://m.media-amazon.com/images/I/61CROuWRV2L._AC_SX395_.jpg",
    img1: "https://m.media-amazon.com/images/I/71-LpDPUDnL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/811JFI9z0kL._AC_SX395_.jpg",
    details:
      "COMFORT AND FIT: These knit ballet flats have a padded insole with high-quality memory foam for added comfort and a heel pillow to relieve pressure and heel slip. The elasticated topline ensures a perfect fit and the knit construction is breathable. Available in regular and wide-widths. If you're between sizes, round up.",
    title: "Knit Ballet Flat",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "flats",
    id: 6,
  },

  {
    img: "https://m.media-amazon.com/images/I/71VaQ+V6XnL._AC_UY695_.jpg",
    img1: "https://m.media-amazon.com/images/I/71HaA6isUxL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71AL8MAJ+BL._AC_SX395_.jpg",
    details:
      "Signature oversized reverse Swoosh on lateral panels. Dual forefoot Zoom Air units for energy return and responsiveness. Rubber outsole with traction pattern inspired by topographical maps for grip in all directions.",
    title: "Nike Zoom Freak",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "green",
    category: "sneakers",
    id: 8,
  },

  {
    img: "https://m.media-amazon.com/images/I/61-cBsLhJHL._AC_UY695_.jpg",
    img1: "https://m.media-amazon.com/images/I/51t3v0drWbL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71b33s3CZqL._AC_SX395_.jpg",
    details:
      "REVOLUTIONARY COMFORT: The Nike Revolution 5 men's running shoes cushion your stride with soft foam to keep you running in comfort. Minimalist design fits in just about anywhere your day takes you.",
    title: "Nike Men's Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Adidas",
    color: "blue",
    category: "sneakers",
    id: 9,
  },

  {
    img: "https://m.media-amazon.com/images/I/71Ul8tduhvL._AC_SX395_.jpg",
    img1: "https://m.media-amazon.com/images/I/81+KyReWo2L._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71cO8fWfQbL._AC_SX395_.jpg",
    details:
      "Axelion Refresh, 37791110, Cool Mid Gray Ultra Blue Puma Black, Medium (D, M). PROFOAM: Lightweight EVA designed to cushion your landing and propel your next step ",
    title: "PUMA Men's Playmaker Pro Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "green",
    category: "sneakers",
    id: 10,
  },
  {
    img: "https://m.media-amazon.com/images/I/71E75yRwCDL._AC_UY575_.jpg",
    img1: "https://m.media-amazon.com/images/I/7106GdadSGL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/61zUyucDrdL._AC_SY395_.jpg",
    details:
      "PERFORMANCE-DRIVEN: With convenient slip-on entry and lace-through midfoot caging for medial and lateral support, these boldly branded kicks are the perfect accompaniment to all your athletic endeavours.",
    title: "Pacer Future Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "red",
    category: "sneakers",
    id: 11,
  },
  {
    img: "https://m.media-amazon.com/images/I/71jeoX0rMBL._AC_UX575_.jpg",
    img1: "https://m.media-amazon.com/images/I/71cuUDCTjEL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71yCRzZbVhL._AC_SX395_.jpg",
    details:
      "SMOOTH AND SNUG: Sleek, streamlined silhouette with synthetic leather upper and midfoot saddle for maximum fit and comfort. CONTEMPORARY DESIGN: Seasonal fracture graphic on this Tazon Cross-Trainer for a modern look.",
    title: "PUMA Men's Tazon 6 Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    id: 12,
  },
  {
    img: "https://m.media-amazon.com/images/I/61TM6Q9dvxL._AC_UX575_.jpg",
    img1: "https://m.media-amazon.com/images/I/71MSSuNyIFL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71TIeHt6T0L._AC_SX395_.jpg",
    details:
      "Retro-inspired sneaker featuring signature Formstrips at sides and T-toe overlay. Cushioned midsole with arch support. Sawtooth traction outsole",
    title: "Roma Basic Sneaker",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "white",
    category: "sneakers",
    id: 13,
  },
  {
    img: "https://m.media-amazon.com/images/I/618GD3N2ylL._AC_SY395_.jpg",
    img1: "https://m.media-amazon.com/images/I/61FLwb9WCDL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71cm+pPdctL._AC_SY395_.jpg",
    details:
      "PERFORMANCE-DRIVEN: With convenient slip-on entry and lace-through midfoot caging for medial and lateral support, these boldly branded kicks are the perfect accompaniment to all your athletic endeavours.",
    title: "Pacer Future Doubleknit",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Puma",
    color: "black",
    category: "sneakers",
    id: 14,
  },

  {
    img: "https://m.media-amazon.com/images/I/81xXDjojYKS._AC_UX575_.jpg",
    img1: "https://m.media-amazon.com/images/I/717TM218cSL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71nvQ0luDKS._AC_SX395_.jpg",
    details:
      "PWRSTRAP FIT SYSTEM-Advanced nylon webbing straps integrated with the lacing system that wrap the foot to provide a secure, personalized fit.",
    title: "Fusion Evo Golf Shoe",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Puma",
    color: "green",
    category: "sneakers",
    id: 15,
  },
  {
    img: "https://m.media-amazon.com/images/I/61BML6O0UIL._AC_SX395_.jpg",
    img1: "https://m.media-amazon.com/images/I/61b0L+N7scS._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71uJQ-CU00S._AC_SX395_.jpg",
    details:
      "Lace up a timeless skate style—now in amazing technicolor—with the new Old Skool Rainbow Chex Checkerboard Skate Shoe from Vans! This vibrant update to the classic Old Skool rocks a sturdy suede and canvas upper with signature side stripes, colorful checkerboard prints, and vulcanized sole construction for flexible grip and traction. ",
    title: "Low-Top Sneakers Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "red",
    category: "sandals",
    id: 16,
  },
  {
    img: "https://m.media-amazon.com/images/I/71gpFHJlnoL._AC_UX575_.jpg",
    img1: "https://m.media-amazon.com/images/I/81G1OfSPfVL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/51T+AbELWNL._AC_SX395_.jpg",
    details:
      "HIGH QUALITY MATERIAL: As a Low Top casual walking shoes，this product adopts breathable canvas vamp plus wear-resistant rubber sole. The insole is soft, fresh and breathable, and the low-top design allows you to wear it in hot summer without feeling uncomfortable. Wearing it for a long time also won't make your feet feel pain.",
    title: "Low-Top Trainers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "white",
    category: "sandals",
    id: 17,
  },
  {
    img: "https://m.media-amazon.com/images/I/71ixBxFytiL._AC_SX395_.jpg",
    img1: "https://m.media-amazon.com/images/I/51BcKF5ArAL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/51gSE-bry2L._AC_SY395_.jpg",
    details:
      "MADE WITH RECYCLED CONTENT: Made with a series of recycled materials, this upper features at least 50% recycled content. This product represents just one of our solutions to help end plastic waste",
    title: "Vans Unisex Low-Top",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "Vans",
    color: "blue",
    category: "sandals",
    id: 18,
  },
  {
    img: "https://m.media-amazon.com/images/I/61N4GyWcHPL._AC_UY575_.jpg",
    img1: "https://m.media-amazon.com/images/I/51dXHcpb7FL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/710993ETSXL._AC_SX395_.jpg",
    details:
      "Lightweight, flexible vulcanized construction with secure bonding between upper and outsole",
    title: "Classic Bandana Sneakers",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "sandals",
    id: 19,
  },
  {
    img: "https://m.media-amazon.com/images/I/61ATrPBvg7L._AC_SX395_.jpg",
    img1: "https://m.media-amazon.com/images/I/81r-EivJuAL._AC_SX395_.jpg",
    img2: "https://m.media-amazon.com/images/I/715VnJoQsIL._AC_SX395_.jpg",
    details:
      "Latest Fashion and Trend for Stylish, Sporty & Sexy look. Imitation Suede / Man Made Leather. Both side Elastic Gore for easy in and out of the boot. Combat Boot with Lug Sole Platform and Chunky Heel 3.5 inches",
    title: "Elastic Gore and Chunky Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "black",
    category: "heels",
    id: 20,
  },
  {
    img: "https://m.media-amazon.com/images/I/51b-OK9ONxL._AC_SY500_.jpg",
    img1: "https://m.media-amazon.com/images/I/51lC9biwpFL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/51t1lN2SdeL._AC_SY395_.jpg",
    details:
      "❥Occasions: Comfortable to wear with, perfect for many occassions such as wedding, party, club, evening, prom, business, dating, photo shoot, outfit, daily wear etc, gift for girlfriend, Valentine's Day, Women's Day",
    title: "Slip On Stiletto High Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "100",
    company: "puma",
    color: "black",
    category: "heels",
    id: 21,
  },
  {
    img: "https://m.media-amazon.com/images/I/71Q3-wzCSPL._AC_SY500_.jpg",
    img1: "https://m.media-amazon.com/images/I/81-cU7D9IYL._AC_SY500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71+uuabrp6L._AC_SY500_.jpg",
    details:
      "Non-Slip Outsole: Enjoy grip and durability with the TPR anti-slip outsole that provides a noise-free experience, perfect for both indoor and outdoor activities. Adjustable Buckle: Customize your fit and add a touch of style with the adjustable buckle that ensures you stay comfortable and chic no matter where your day takes you.",
    title: "DREAM PAIRS Court Shoes",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Nike",
    color: "red",
    category: "heels",
    id: 22,
  },

  {
    img: "https://m.media-amazon.com/images/I/51Q16iN5lsL._AC_SY395_.jpg",
    img1: "https://m.media-amazon.com/images/I/61a7b2vvNsL._AC_SY395_.jpg",
    img2: "https://m.media-amazon.com/images/I/71gyleEVlaL._AC_SY395_.jpg",
    details:
      "The Shoes are perfect for walking or driving with beautiful and recognizable bottom pattern design,it shows high quality from details. Choose these comfy flats when taking off heels.",
    title: "Loafer Flats",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Vans",
    color: "white",
    category: "flats",
    id: 7,
  },

  {
    img: "https://m.media-amazon.com/images/I/61iyXdZR1gL._AC_SX679_.jpg",
    img1: "https://m.media-amazon.com/images/I/51XDUQh1D+L._AC_SX466_.jpg",
    img2: "https://m.media-amazon.com/images/I/51FbseUybQL._AC_SX466_.jpg",
    details:
      "Air Cushion Design:Running shoes use air cushion design to provide cushioning and support for the feet. The soft and comfortable touch can effectively relieve your fatigue and discomfort during travel and sports, perfect accord with human body engineering provide more the protection of the foot and knees.",
    title: "Nike Air Vapormax Plus+",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "gray",
    category: "sneakers",
    id: 23,
  },

  {
    img: "https://m.media-amazon.com/images/I/61FqW-LNXKL._AC_SY500_.jpg",
    img1: "https://m.media-amazon.com/images/I/81pelETBU9L._AC_SY500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71LM-lzjE4L._AC_SY500_.jpg",
    title: "Low Mid Block Heels",
    details:
      "【Non-slip outsole】Non-slip TPR rubber outsole for steady and safe steps could ideally bring your confidence in every step when standing in them to anywhere. [Occasions】Women's ankle strap low heels put a perfect finish on any outfit for Wedding, Date, Office Work, Daily, Party, Cocktail, Homecoming, Prom or other special occasions.",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "200",
    company: "Nike",
    color: "black",
    category: "heels",
    id: 24,
  },
  {
    img: "https://m.media-amazon.com/images/I/71DWKjgksAL._AC_SY500_.jpg",
    img1: "https://m.media-amazon.com/images/I/61rnoojBR2L._AC_SY500_.jpg",
    img2: "https://m.media-amazon.com/images/I/61Cyb36ue6L._AC_SY500_.jpg",
    details:
      "Bold Block Heel: Set on a sturdy chunky heel that provides support even when you’re on your feet all night. Take your look to new heights in these women’s pumps. Fashion-Forward: Amp up any outfit with these platform pumps that can be styled with just about anything in your wardrobe for an effortless off-duty look.",
    title: "Chunky High Heel+",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
    id: 25,
  },
  {
    img: "https://m.media-amazon.com/images/I/71iX3CoNNcL._AC_SY500_.jpg",
    img1: "https://m.media-amazon.com/images/I/717Dg-ADWeL._AC_SY500_.jpg",
    img2: "https://m.media-amazon.com/images/I/712UhrfHKUL._AC_SY500_.jpg",
    details:
      "High Stilettos Platform Heel, Heel measures approximately 5 inches, Platform height: 1.25 inches (Approx). Fabric upper with rhinestone embellishments. Ankle strap with buckle closure. Peep-toe silhouette.Finished with a slightly padded faux leather insole. TPR rubber out-sole.",
    title: "DREAM PAIRS Women's Heeled Sandals Pump",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "150",
    company: "Adidas",
    color: "white",
    category: "heels",
    id: 26,
  },
  {
    img: "https://m.media-amazon.com/images/I/61QhyiBkVpL._AC_SY395_.jpg",
    img1: "https://m.media-amazon.com/images/I/61wxJLeH+zL._AC_SY500_.jpg",
    img2: "https://m.media-amazon.com/images/I/71gbhKDkYLL._AC_SY500_.jpg",
    details:
      "👑 👡 Fit well: Are you worried about not fitting? GENSHUO Low Block Heels are handmade, not only of high quality, but also fitful. Standard US Size,true to size fit, both in length and width, you can choose the appropriate size according to your own situation. (If the size is not suitable, free return and exchange).",
    title: "GENSHUO Women Open Toe Ankle Strap",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
    id: 27,
  },
  {
    img: "https://m.media-amazon.com/images/I/61veBkOZE-L._AC_SY500_.jpg",
    img1: "https://m.media-amazon.com/images/I/51gJxnTFU+L._AC_SY575_.jpg",
    img2: "https://m.media-amazon.com/images/I/51Hf-5SumAL._AC_SY500_.jpg",
    details:
      "Material: High-quality faux leather and soft premium material, these are suitable for everyday wear. The sandals provide great anti skid and also for a pleasurable walking experience. Design: Square opening toe design, elegant ankle strap, with kitten heels that can show your body and lengthen the curve of the leg, make you look slim and charming.",
    title: "Strappy Sandals Kitten Heel",
    star: <AiFillStar className="rating-star" />,
    reviews: "(123 reviews)",
    sold: "1k+ sold",
    prevPrice: "$140,00",
    newPrice: "50",
    company: "Adidas",
    color: "black",
    category: "heels",
    id: 28,
  },
];

export default data;
